services:
  test:
    build: .
    image: backend:latest
    env_file: .env.test
    depends_on:
      migrations:
        condition: service_completed_successfully
    command: python -m pytest -v
    volumes:
      - ./app:/fast_app/app
      - ./migrations:/fast_app/migrations
      - ./tests:/fast_app/tests

  migrations:
    image: backend:latest
    env_file: .env.test
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/fast_app/app
      - ./migrations:/fast_app/migrations

  db:
    image: postgres:18-alpine3.23
    env_file: .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
