"""empty message

Revision ID: e7daa1b598da
Revises: 
Create Date: 2026-05-14 17:26:27.062289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7daa1b598da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(), nullable=False),
    sa.Column('sleep', sa.Float(), nullable=False),
    sa.Column('sugar_intake', sa.String(), nullable=False),
    sa.Column('smoking', sa.String(), nullable=False),
    sa.Column('alcohol', sa.String(), nullable=False),
    sa.Column('married', sa.String(), nullable=False),
    sa.Column('profession', sa.String(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('predict', sa.Integer(), nullable=False),
    sa.Column('predict_proba', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    # ### end Alembic commands ###
